float:
  any:
  - base_args: ['@metric']
    constructor: clickhouse
    disabled: false
    docker_tag: ann-benchmarks-clickhouse
    module: ann_benchmarks.algorithms.clickhouse
    name: clickhouse
    run_groups:
      M-64:
        arg_groups: [{M: 64, efConstruction: 400}]
        args: {}
        query_args: [[10, 20, 40, 200, 400]]
